### ISSUE TITLE
step 4の心理的難易度の参考文献について

### ISSUE THREAD

**Issue by yebityon** [kamuiroeru/cs2020-group6#2]
Bavota G, Canfora G, Di Penta M, Oliveto R, Panichella S (2015) How the apache community upgrades dependencies: an evolutionary study. Empirical Softw Eng 20(5):1275–1317. ISSN 1382–3256
が正しいです....すいません……

**Comment by kamuiroeru** [comment]
あ… 僕がやらかしてますね…
すみません。 Google検索して一番上に出てきたやつを脳死で引用してました。
本当ごめんなさい…修正しました
